apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-zookeeper-0
  namespace: default
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /var/lib/zookeeper/data
